### ISSUE TITLE
Output and Extend output function

### ISSUE THREAD

**Issue by twaston** [tugkan/apartments-scraper#1]
Hi Tuğkan,

I am the user of your apartments.com scraper on apify. I have a few questions about the scraper.
1. I create the task and I find the output is not as same as the example you provided. It missing many parts compared with your output. Below is the result I got. I need Property Information, Community Amenities, Apartment Features on the website, such as year built and stories. I am wondering if it is possible to get those, or if there is a way I could add those to the result. I do notice that the extendOutputFunction option on the input page. Since I am not very familiar with JavaScript, would you please give a sample input and output indicating how to set the parameter's of this function, 
Thank you so much! Looking forward to your response!

Best,
Tiffany 

 [{
  "id": "e9xq8rq",
  "propertyName": "ParkLine Miami",
  "url": "https://www.apartments.com/parkline-miami-miami-fl/e9xq8rq/",
  "breadcrumbs": [
    "Home",
    "Florida",
    "Miami",
    "ParkLine Miami"
  ],
  "location": {
    "fullAddress": "100 NW 6th St Miami FL 33136",
    "state": "Florida",
    "city": "Miami",
    "neighborhood": "City Center Miami",
    "postalCode": "33136",
    "streedAddress": "100 NW 6th St"
  },
  "rating": 4.9,
  "isVerified": true,
  "rent": {
    "min": 1950,
    "max": 5230
  },
  "beds": "Studio - 3 bd",
  "baths": "1 - 3.5 ba",
  "sqft": "572 - 2,865 sq ft",
  "transitAndPOI": [],
  "scores": {
    "walkScore": 91,
    "transitScore": 79
  },
  "neighborhoodDescription": "",
  "schools": {
    "public": [],
    "private": []
  },
  "fees": {
    "oneTimeFees": {},
    "monthlyFees": {}
  },
  "description": "About ParkLine Miami\n                            Welcome to world-class living at ParkLine Miami, perched above downtown with stunning panoramic views of the cityscape, ocean and Biscayne Bay. At ParkLine Miami, immerse yourself in an oasis of health and wellness with a two-acre outdoor SkyPark. Easily connect your social and leisure life in a centrally located address, all moments away from some of Miami?s most iconic and sought-after neighborhoods, restaurants and shopping. From sunset to jet set, reset with your new lifestyle.\n\n                    \n                    ParkLine Miami is an apartment located in Miami/Dade County, the 33136 ZIP Code, and the Miami-Dade attendance zone.",
  "amenities": [],
  "contact": {
    "phone": "844-238-7400844-238-7400",
    "name": ""
  },
  "models": [
    {
      "modelName": "Studio-SS1 South Residence",
      "rentLabel": "$1,950 – $2,175",
      "details": [
        "Studio",
        "1 bath",
        "572 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "Studio-SN2 North Residence",
      "rentLabel": "$2,275 – $2,295",
      "details": [
        "Studio",
        "1 bath",
        "630 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "Studio-SN1 North Residence",
      "rentLabel": "$2,275 – $2,325",
      "details": [
        "Studio",
        "1 bath",
        "646 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "1 Bed/1 Bath-AS4 South Residence",
      "rentLabel": "$2,600 – $2,950",
      "details": [
        "1 bed",
        "1 bath",
        "748 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "1 Bed/1 Bath-AS3 South Residence",
      "rentLabel": "$2,600 – $2,950",
      "details": [
        "1 bed",
        "1 bath",
        "760 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "1 Bed/1 Bath-AS2 South Residence",
      "rentLabel": "$2,700 – $2,900",
      "details": [
        "1 bed",
        "1 bath",
        "709 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "1 Bed/1 Bath-As6 South Residence",
      "rentLabel": "$2,750 – $2,775",
      "details": [
        "1 bed",
        "1 bath",
        "763 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "1 Bed/1 Bath-AN3 North Residence",
      "rentLabel": "$2,750 – $2,795",
      "details": [
        "1 bed",
        "1 bath",
        "735 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "1 Bed/1 Bath-AS1 South Residence",
      "rentLabel": "$2,775 – $2,950",
      "details": [
        "1 bed",
        "1 bath",
        "783 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "1 Bed/1 Bath-AN1 North Residence",
      "rentLabel": "$2,795 – $2,895",
      "details": [
        "1 bed",
        "1 bath",
        "840 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "1 Bed/1 Bath-AS5 South Residence",
      "rentLabel": "$2,900 – $3,050",
      "details": [
        "1 bed",
        "1 bath",
        "868 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "1 Bed/1.5 Bath Den-AN4 North Residence",
      "rentLabel": "$3,200 – $3,295",
      "details": [
        "1 bed",
        "1.5 baths",
        "952 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/2 Bath-BN3 North Residence",
      "rentLabel": "$3,320 – $4,150",
      "details": [
        "2 beds",
        "2 baths",
        "1,432 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/2 Bath-BS2 South Residence",
      "rentLabel": "$3,725 – $3,995",
      "details": [
        "2 beds",
        "2 baths",
        "1,052 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/2 Bath Penthouse-PH BS1 South Residence",
      "rentLabel": "$5,230",
      "details": [
        "2 beds",
        "2 baths",
        "1,493 sq ft",
        "Available Now"
      ],
      "leaseOptions": "Available Now",
      "availability": "",
      "units": []
    },
    {
      "modelName": "1 Bed/1 Bath Den-AN2 North Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "1 bed",
        "1 bath",
        "908 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "1 Bed/1 Bath-PH-AN1 North Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "1 bed",
        "1 bath",
        "1,077 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/2.5 Bath Den-BN1 North Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "2 beds",
        "2.5 baths",
        "1,314 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/2 Bath-PH-BN1 North Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "2 beds",
        "2 baths",
        "1,495 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/2.5 Bath Den-BN2 North Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "2 beds",
        "2.5 baths",
        "1,336 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/2.5 Bath-PH-BN2 North Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "2 beds",
        "2.5 baths",
        "1,522 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/2.5 Bath-BN4 North Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "2 beds",
        "2.5 baths",
        "1,624 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/2.5 Bath-BN3 North Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "2 beds",
        "2.5 baths",
        "1,643 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/1.5 Bath Penthouse-PH - BS3 South Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "2 beds",
        "1.5 baths",
        "1,313 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/2 Bath-BS1 South Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "2 beds",
        "2 baths",
        "1,179 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/2 Bath Penthouse-PH - BS2 South Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "2 beds",
        "2 baths",
        "1,396 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/2 Bath Penthouse-Ph - BS5 South Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "2 beds",
        "2 baths",
        "1,428 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/2 Bath Penthouse-PH - BS6 South Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "2 beds",
        "2 baths",
        "1,428 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "2 Bed/2.5 Bath Penthouse-PH - BS4 South Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "2 beds",
        "2.5 baths",
        "1,440 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "3 Bed/3.5 Bath-PH-CN1 North Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "3 beds",
        "3.5 baths",
        "2,865 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    },
    {
      "modelName": "3 Bed/3 Bath-CS1 South Residence",
      "rentLabel": "Call for Rent",
      "details": [
        "3 beds",
        "3 baths",
        "1,429 sq ft",
        "Not Available"
      ],
      "leaseOptions": "Not Available",
      "availability": "",
      "units": []
    }
  ],

**Comment by tugkan** [comment]
@twaston Hey there. Thank you for using the actor. The actor have been fixed and can be used for further development. For extending the output function it'd be better to submit a project to Apify Marketplace if it is necessary.
