### ISSUE TITLE
Scraper Output Fields

### ISSUE THREAD

**Issue by B3autiful-Oblivion** [tugkan/apartments-scraper#2]
Hello, this app is great! I just want to know if there is a way to limit the output fields to a pre-set selection. For example: beds, baths, rent, sqft, etc...

**Comment by tugkan** [comment]
Hey @B3autiful-Oblivion ! Thanks for using the actor.

The actor doesn't support that functionality in a built-in manner. However through Apify you can use `fields` parameter on the URL. Example:

```
https://api.apify.com/v2/datasets/XXXXX/items?clean=true&fields=title,url
```
