### ISSUE TITLE
How to scrape all apartment  information?

### ISSUE THREAD

**Issue by sky1122** [tugkan/apartments-scraper#3]
Hi~ this app is excellent! I just want to know if there is a way to scrape all the pages instead of change Start URLs for every page?

**Comment by sky1122** [comment]
My input is here, But it can only scrape first page items
{
  "startUrls": [
    "https://www.apartments.com/314-s-state-st-champaign-il/c74n4wf/",
    "https://www.apartments.com/champaign-il/2/?bb=ljtyt4jwsJ6_n6puB"
  ],
  "endPage": 25,
  "proxy": {
    "useApifyProxy": true
  },
  "extendOutputFunction": "($) => { return {} }",
  "maxItems": 50
}

**Comment by sky1122** [comment]
When I try to use another startURL it works, But after few pages, the same error appear
![image](https://user-images.githubusercontent.com/48091236/135939511-c5cdf40d-3a0e-4638-a3f1-d62e73f22704.png)

**Comment by tugkan** [comment]
Thank you very much for this bug report. The issue has been fixed and it is ready for use.
