### ISSUE TITLE
Thank you for updating, but a another problem appear

### ISSUE THREAD

**Issue by sky1122** [tugkan/apartments-scraper#4]
These are my input startURL
1.
View in another windowDownloadCopy to clipboard
{
  "startUrls": [
    "https://www.apartments.com/lancaster-apartments-champaign-il/7jkpfzy/",
    "https://www.apartments.com/champaign-il/?bb=62lh5375rJ8xyw6B/"
  ],
  "endPage": 25,
  "maxItems": 100000000,
  "proxy": {
    "useApifyProxy": true
  },
  "extendOutputFunction": "($) => { return {} }"
}
2. example on the home page.

All of them will have this error message
![image](https://user-images.githubusercontent.com/48091236/136098629-c5569688-9818-4b4f-b6f9-98a5cb19a794.png)
thank you so much

**Comment by tugkan** [comment]
Hey there again. Thanks for reporting this. The issue has been resolved. Sorry for the inconvenience.

Best.
