### ISSUE TITLE
Only Returns First Page

### ISSUE THREAD

**Issue by iAmKevinMcKee** [tugkan/apartments-scraper#5]
First of all, this is amazing. Thank you so much for this scraper.

I tried to get all properties from this page: https://www.apartments.com/pinellas-county-fl/under-1300/

It returned the first 25 results, but there are actually 60 across 3 pages. Here was the input I used:

```JSON
{
  "startUrls": [
    "https://www.apartments.com/pinellas-county-fl/under-1300/"
  ],
  "extendOutputFunction": "($) => { return {} }",
  "proxy": {
    "useApifyProxy": true
  },
  "maxItems": 500,
  "endPage": 3
}
```

Was there a problem with my input? How can I get all 60 properties?

**Comment by tugkan** [comment]
@iAmKevinMcKee Thank you for the report. We've fixed the issue and you can use it safely now. Please use the last version of the actor.

Best!
