### ISSUE TITLE
Issue with parsing custom filtering / drawn map

### ISSUE THREAD

**Issue by snarf2larf** [tugkan/apartments-scraper#6]
If you draw a custom map with filtering, it seems to ignore the `?sk=...` portion of the URL to pull the properties you have drawn a map around.

Example input:

```json
{
    "startUrls": [
        "https://www.apartments.com/apartments-condos/?sk=b750ffdad9e5386faf6ea5b05a88033d&bb=vuvyskjmmN0qv6x9wB"
    ],
    "extendOutputFunction": "($) => { return {} }",
    "proxy": {
        "useApifyProxy": true
    }
}
```

Debug output shows it only attempting to parse from: `https://www.apartments.com/apartments-condos`

```
INFO  CRAWLER: -- Fetching list: https://www.apartments.com/apartments-condos with page: 1
```

This ends up pulling data from Buffalo, NY instead of the drawn map which should be only data from the Las Vegas, NV area:

```
2022-08-05T17:16:38.544Z INFO  CRAWLER: -- Fetching url: https://www.apartments.com/the-residences-at-279-north-buffalo-ny/3p3405e/
```

**Comment by tugkan** [comment]
Hey @snarf2larf 

The problem should be gone now. You can use the latest version.

Best
