### ISSUE TITLE
Property Information

### ISSUE THREAD

**Issue by HLJman** [tugkan/apartments-scraper#7]
Feature Request. 

Apartments.com provides property details such as year built, total units. It would be nice if this information could be scraped as well. 
![Screenshot 2023-03-01 at 9 12 04 AM](https://user-images.githubusercontent.com/33382580/222197156-61867a92-ed81-43c0-96db-8021ec88beed.png)

**Comment by tugkan** [comment]
Hey @HLJman !

The information that you are looking for can be found inside the `fees` array with the title `Property Information`.

Best
